import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// ── Translations ─────────────────────────────────────────────────────────────
export const TRANSLATIONS = {
  en: {
    // Sidebar nav
    nav_dashboard: 'Dashboard',
    nav_courses: 'Courses',
    nav_my_courses: 'My Courses',
    nav_labs: 'Labs',
    nav_leaderboard: 'Leaderboard',
    nav_profile: 'Profile',
    nav_users: 'Users',
    nav_students: 'Students',
    nav_analytics: 'Analytics',
    nav_subscriptions: 'Subscriptions',
    nav_course_builder: 'Course Builder',
    nav_sign_out: 'Sign Out',
    nav_admin_panel: 'Admin Panel',

    // TopBar & common
    search_placeholder: 'Search courses, labs, and topics...',
    preview_admin: '👤 My View (Admin)',
    preview_master: '📋 Preview as Master',
    preview_participant: '🎓 Preview as Participant',

    // Course page
    enroll_now: 'Enroll Now — Free',
    enrolled: 'Enrolled',
    back_to_courses: 'Back to Courses',
    course_content: 'Course Content',
    lessons: 'lessons',
    enrolled_count: 'enrolled',
    completed: 'completed',
    learning_path: 'Learning Path',
    up_next: '▶ UP NEXT',
    done: '✓ DONE',
    get_certificate: '🎓 Get Certificate',
    course_complete_title: '🏅 Course Complete!',
    course_complete_body: "You've finished all lessons in this course. Outstanding work!",

    // Lesson page
    back_to_course: 'Back to Course',
    complete_lesson: 'Complete Lesson',
    already_completed: 'Completed',
    next: 'Next',
    previous: 'Previous',
    processing: 'Processing...',
    what_youll_learn: "What you'll explore in this lesson",
    how_was_lesson: 'How was this lesson?',
    thanks_feedback: '✅ Thanks for your feedback!',
    lesson_label: 'Lesson',
    of: 'of',
    watch_on: 'Watch on',

    // Labs
    run_code: 'Run Code',
    submit_task: 'Submit Task',
    reset: 'Reset',
    terminal: 'Terminal',
    ai_hints: 'AI Hints',
    reveal_hint: 'Reveal Hint',
    all_hints_revealed: "All hints revealed. You've got this! 💪",
    mission_accomplished: 'Mission Accomplished! 🏅',
    return_to_hub: 'Return to Hub',
    ai_feedback: 'AI Reviewer Feedback',
    running: 'Running…',

    // Onboarding
    onboard_title_1: 'Welcome to Promptara!',
    onboard_sub_1: 'Your AI Coding Academy',
    onboard_title_2: 'How It Works',
    onboard_sub_2: 'Learn in 4 simple steps',
    onboard_title_3: 'XP & Levels Explained',
    onboard_sub_3: 'Your progress, gamified',
    onboard_title_4: "You're All Set!",
    onboard_sub_4: 'Time to start your first lesson',
    onboard_start: '🚀 Start Learning!',
    onboard_next: 'Next',
    onboard_back: '← Back',

    // Notifications
    notif_title: 'Notifications',
    notif_subtitle: 'Recent activity',
    notif_empty: 'No recent activity yet. Start a lesson!',
    notif_footer: 'Only lesson completions are shown',
    notif_completed: 'Completed',

    // Guided tour
    tour_dont_show: "Don't show again",
    tour_done: '✓ Done',
    tour_next: 'Next',

    // Page titles
    page_dashboard: 'Dashboard',
    page_dashboard_sub: 'Welcome back! Keep learning.',
    page_courses: 'Courses',
    page_courses_sub: 'Browse and continue your learning journey',
    page_labs: 'Labs',
    page_labs_sub: 'Hands-on simulations and challenges',
    page_leaderboard: 'Leaderboard',
    page_leaderboard_sub: 'Top vibe coders this month',
    page_profile: 'My Profile',
    page_profile_sub: 'Your learning stats and achievements',
    page_users: 'User Management',
    page_users_sub: 'Manage platform members',
    page_builder: 'Course Builder',
    page_builder_sub: 'Create and manage course content',
    page_analytics: 'Analytics',
    page_analytics_sub: 'Platform usage and insights',
    page_subs: 'Subscriptions',
    page_subs_sub: 'Manage SaaS plans and billing',

    // XP
    xp_level: 'Level',
    xp_to_next: 'to next',

    // Lesson details & Quiz
    time_min: 'min',
    quiz_req: 'Quiz — 80% to pass',
    watch_read: 'Watch & Read',
    read_practice: 'Read & Practice',
    xp_on_completion: 'XP on completion',
    your_turn: 'Your Turn!',
    correct: 'Correct!',
    correct_answer: 'Correct answer:',
    type_answer: 'Type your answer...',
    true_ans: 'True',
    false_ans: 'False',
    check: 'Check',

    // Sprint 1 — Friendly Microcopy
    start_here_title: "👋 New here? Start with these!'",
    start_here_sub: "Don't worry, no coding experience needed. We'll guide you step by step.",
    start_here_cta: 'See All Beginner Courses →',
    no_course_active: "You haven't started any course yet. Let's begin your journey! 🚀",
    browse_free: 'Explore Free Courses →',
    complete_lesson_cta: 'Mark Complete & Earn',
    error_generic: 'Something went wrong. Please try refreshing the page 🙏',
    no_results_search: "Hmm, nothing matched. Try removing filters or searching with different keywords!",
    quiz_score_live: 'correct so far',
    quiz_need_more: 'more correct to pass',
    quiz_ready_to_pass: "You're on track to pass! ✅",
    quiz_all_correct: 'Perfect score! 🎉',
    xp_benefits_title: 'What XP unlocks for you',
    xp_benefits_sub: 'Keep learning to reach new milestones',
    xp_benefit_1: 'Access all Beginner courses',
    xp_benefit_2: 'Unlock Intermediate courses',
    xp_benefit_3: 'Access exclusive Labs',
    xp_benefit_4: 'Earn digital certificate',
    xp_benefit_5: '"Vibe Coder" badge + priority support',
    nav_courses_sub: 'Learning materials',
    nav_labs_sub: 'Coding practice',
    nav_leaderboard_sub: 'Your ranking',
    nav_dashboard_sub: 'Overview',
    nav_profile_sub: 'Settings & stats',
    streak_day: 'day streak',
    streak_days: 'day streak',

    // Sprint 2 - Weekly challenge & Roadmap & Badges
    weekly_challenge_title: 'Weekly Personal Challenge',
    weekly_challenge_sub: 'Keep your momentum going! Complete lessons to earn bonus XP.',
    weekly_challenge_target: 'Complete 3 lessons this week',
    weekly_challenge_reward: 'Reward:',
    weekly_challenge_deadline: 'Ends on',
    weekly_challenge_completed: 'Challenge Completed! 🎉',
    weekly_challenge_progress: 'lessons completed',
    
    badge_locked_title: 'Achievements & Badges',
    badge_locked_subtitle: 'Show off your progress and unlock special status',
    badge_condition_first_lab: 'Complete your first hands-on lab',
    badge_condition_graduate_1: 'Complete 1 course',
    badge_condition_graduate_2: 'Complete 2 courses',
    badge_condition_graduate_3: 'Complete 3 courses',
    badge_condition_graduate_4: 'Complete 4 courses',
    badge_condition_graduate_5: 'Complete 5 courses',
    badge_condition_speed_demon: 'Complete 3 lessons in a single day',
    badge_condition_perfectionist: 'Get a perfect 100% score on a quiz',
    
    roadmap_title: 'Learning Roadmap',
    roadmap_sub: 'Your guided path from absolute beginner to advanced builder',
    roadmap_tier_beginner: '🌱 Beginner',
    roadmap_tier_explorer: '🔥 Explorer',
    roadmap_tier_vibecoder: '🚀 Vibe Coder',
    roadmap_tier_advanced: '💡 Advanced Builder',
    roadmap_tier_desc_beginner: 'IT Basics & Setup',
    roadmap_tier_desc_explorer: 'Prompting Fundamentals',
    roadmap_tier_desc_vibecoder: 'AI Apps Development',
    roadmap_tier_desc_advanced: 'Production & Deploy',
    roadmap_here: 'You are here',
    
    quiz_review_title: 'Review Mode',
    quiz_review_subtitle: 'Review the questions you got wrong and try again!',
    quiz_try_again: 'Try Again',

    // Course Quizzes
    'In the Vibe Coding paradigm, what is the primary role of the human developer?': 'In the Vibe Coding paradigm, what is the primary role of the human developer?',
    'Writing boilerplate code manually': 'Writing boilerplate code manually',
    'Memorizing syntax': 'Writing boilerplate code manually',
    'Acting as the Director and Architect': 'Acting as the Director and Architect',
    'Replacing the compiler': 'Replacing the compiler',
    'The human transitions from being the typist to being the architect, focusing on system design and validation.': 'The human transitions from being the typist to being the architect, focusing on system design and validation.',
    'AI models have perfect memory of your codebase once you start a conversation.': 'AI models have perfect memory of your codebase once you start a conversation.',
    'AI models are stateless. You must load context explicitly in every session or conversation.': 'AI models are stateless. You must load context explicitly in every session or conversation.',
    'Arrange these Vibe Coding workflow steps in the correct order:': 'Arrange these Vibe Coding workflow steps in the correct order:',
    'Step 1: Define the goal and scope of the feature': 'Step 1: Define the goal and scope of the feature',
    'Step 2: Load context — describe tech stack and constraints': 'Step 2: Load context — describe tech stack and constraints',
    'Step 3: Write a specific, scoped prompt to the AI': 'Step 3: Write a specific, scoped prompt to the AI',
    'Step 4: Review every line of the AI-generated code': 'Step 4: Review every line of the AI-generated code',
    'Step 5: Commit the working code to Git': 'Step 5: Commit the working code to Git',
    'The correct order ensures the AI has all context before generating, and you verify before shipping.': 'The correct order ensures the AI has all context before generating, and you verify before shipping.',
    'What is the main benefit of Chain of Thought (CoT) prompting?': 'What is the main benefit of Chain of Thought (CoT) prompting?',
    'It uses fewer tokens': 'It uses fewer tokens',
    'It forces the model to write out reasoning steps, reducing logical errors': 'It forces the model to write out reasoning steps, reducing logical errors',
    'It guarantees 100% secure code': 'It guarantees 100% secure code',
    'It prevents the model from using external tools': 'It prevents the model from using external tools',
    'CoT allows the model to "show its work", which drastically improves its ability to solve complex logical problems.': 'CoT allows the model to "show its work", which drastically improves its ability to solve complex logical problems.',
    'Which of the following is an example of Few-Shot Prompting?': 'Which of the following is an example of Few-Shot Prompting?',
    '"Write a web server in Go."': '"Write a web server in Go."',
    '"Let\'s think step by step."': '"Let\'s think step by step."',
    'Providing 3 examples of inputs and desired outputs before asking the real question.': 'Providing 3 examples of inputs and desired outputs before asking the real question.',
    '"Act as a senior engineer."': '"Act as a senior engineer."',
    'Few-shot prompting relies on providing concrete examples (shots) to guide the model\'s output formatting.': 'Few-shot prompting relies on providing concrete examples (shots) to guide the model\'s output formatting.',
    'Why should you avoid asking the AI to "build the whole app" in one prompt?': 'Why should you avoid asking the AI to "build the whole app" in one prompt?',
    'Because it costs too much money': 'Because it costs too much money',
    'Because of token limits and attention degradation leading to poor code quality': 'Because of token limits and attention degradation leading to poor code quality',
    'Because AI cannot write full apps': 'Because AI cannot write full apps',
    'Because the compiler will reject it': 'Because the compiler will reject it',
    'LLMs perform best on scoped, modular tasks. Asking for massive files at once leads to errors and truncated code.': 'LLMs perform best on scoped, modular tasks. Asking for massive files at once leads to errors and truncated code.',
    'What is the recommended way to fix a broken UI generated by AI?': 'What is the recommended way to fix a broken UI generated by AI?',
    'Spend hours manually reading CSS documentation': 'Spend hours manually reading CSS documentation',
    'Delete the project and start over': 'Delete the project and start over',
    'Provide the AI with a screenshot of the broken UI and ask it to fix the layout': 'Provide the AI with a screenshot of the broken UI and ask it to fix the layout',
    'Switch to a different programming language': 'Switch to a different programming language',
    'Using Multimodal (Vision) AI is the fastest way to debug visual alignment and CSS issues.': 'Using Multimodal (Vision) AI is the fastest way to debug visual alignment and CSS issues.',
    'What is a "hallucination" in the context of AI coding?': 'What is a "hallucination" in the context of AI coding?',
    'When the AI writes perfectly optimized code': 'When the AI writes perfectly optimized code',
    'When the AI confidently generates code that uses non-existent functions or libraries': 'When the AI confidently generates code that uses non-existent functions or libraries',
    'When the AI refuses to answer': 'When the AI refuses to answer',
    'When the AI deletes your files': 'When the AI deletes your files',
    'Hallucinations occur when the model predicts tokens that look plausible but are factually incorrect or reference non-existent APIs.': 'Hallucinations occur when the model predicts tokens that look plausible but are factually incorrect or reference non-existent APIs.',
    'What is the best defense against AI hallucinations in JavaScript?': 'What is the best defense against AI hallucinations in JavaScript?',
    'Using TypeScript for static type checking': 'Using TypeScript for static type checking',
    'Using `var` instead of `const`': 'Using `var` instead of `const`',
    'Writing all code in a single file': 'Writing all code in a single file',
    'Never using AI': 'Never using AI',
    'TypeScript catches hallucinations at compile time by ensuring the AI-generated code adheres to defined interfaces and types.': 'TypeScript catches hallucinations at compile time by ensuring the AI-generated code adheres to defined interfaces and types.',
    'What is Prompt Injection?': 'What is Prompt Injection?',
    'Injecting SQL commands into a database': 'Injecting SQL commands into a database',
    'When a user crafts input that overrides the LLM system instructions to make it perform unauthorized actions': 'When a user crafts input that overrides the LLM system instructions to make it perform unauthorized actions',
    'A way to make the AI respond faster': 'A way to make the AI respond faster',
    'Injecting CSS into a webpage': 'Injecting CSS into a webpage',
    'Prompt injection is unique to LLMs, where untrusted user input tricks the model into ignoring its original constraints.': 'Prompt injection is unique to LLMs, where untrusted user input tricks the model into ignoring its original constraints.',
    'How should you handle the output of an LLM before using it to execute a system command or database query?': 'How should you handle the output of an LLM before using it to execute a system command or database query?',
    'Trust it completely if it comes from GPT-4': 'Trust it completely if it comes from GPT-4',
    'Pass it directly to the database': 'Pass it directly to the database',
    'Force structured JSON output and strictly validate it against a predefined schema': 'Force structured JSON output and strictly validate it against a predefined schema',
    'Only run it on Tuesdays': 'Only run it on Tuesdays',
    'Never trust LLM output. Always force a structured format (like JSON) and validate it using a schema validation library before execution.': 'Never trust LLM output. Always force a structured format (like JSON) and validate it using a schema validation library before execution.',

    // Learning Resources
    'Review: Vibe Coding Overview': 'Review: Vibe Coding Overview',
    'What is Vibe Coding? (GitHub Blog)': 'What is Vibe Coding? (GitHub Blog)',
    'GitHub Copilot Documentation': 'GitHub Copilot Documentation',
    'Awesome AI Dev Tools': 'Awesome AI Dev Tools',
    'Course Companion Notes': 'Course Companion Notes',
    'Lesson Cheatsheet': 'Lesson Cheatsheet',
    'Review the Lesson Content': 'Review the Lesson Content',
    'Quiz Strategies for Beginners': 'Quiz Strategies for Beginners',

    // Resource Types
    Docs: 'Docs',
    Repository: 'Repository',
    Cheatsheet: 'Cheatsheet',
    Article: 'Article',
    Download: 'Download',

    // Sprint 3 - Labs sorting, Guided Mode, Explain Code, Certificate
    sort_by_level: 'Sort by Level:',
    sort_default: 'Default',
    sort_beginner_first: '🌱 Beginner First',
    sort_advanced_first: '🚀 Advanced First',
    guided_mode_toggle: 'Guided Mode',
    expert_mode: 'Expert',
    guided_mode: 'Guided',
    guided_checklist_title: 'Guided Checklist',
    guided_checklist_subtitle: 'Step-by-step instructions to help you complete this lab',
    explain_code_btn: '💡 Explain Code',
    explain_code_title: 'Code Breakdown',
    explain_code_subtitle: 'Line-by-line explanation of your starter code in simple terms',
    explain_code_close: 'Close',
    certificate_modal_title: 'PROMPTARA CERTIFICATE OF COMPLETION',
    certificate_presented_to: 'This is proudly presented to',
    certificate_course_completed: 'for successfully completing the course',
    certificate_role: 'Certified Digital Builder',
    certificate_date: 'Date of Completion',
    certificate_id: 'Credential ID',
    certificate_print: 'Save Certificate (PDF)',
  },

  id: {
    // Sidebar nav
    nav_dashboard: 'Dasbor',
    nav_courses: 'Kursus',
    nav_my_courses: 'Kursus Saya',
    nav_labs: 'Laboratorium',
    nav_leaderboard: 'Papan Peringkat',
    nav_profile: 'Profil',
    nav_users: 'Pengguna',
    nav_students: 'Peserta Didik',
    nav_analytics: 'Analitik',
    nav_subscriptions: 'Langganan',
    nav_course_builder: 'Pembuat Kursus',
    nav_sign_out: 'Keluar',
    nav_admin_panel: 'Panel Admin',

    // TopBar & common
    search_placeholder: 'Cari kursus, lab...',
    preview_admin: '👤 Tampilan Saya (Admin)',
    preview_master: '📋 Pratinjau sebagai Master',
    preview_participant: '🎓 Pratinjau sebagai Peserta',

    // Course page
    enroll_now: 'Daftar Sekarang — Gratis',
    enrolled: 'Sudah Terdaftar',
    back_to_courses: 'Kembali ke Kursus',
    course_content: 'Konten Kursus',
    lessons: 'pelajaran',
    enrolled_count: 'terdaftar',
    completed: 'selesai',
    learning_path: 'Jalur Belajar',
    up_next: '▶ SELANJUTNYA',
    done: '✓ SELESAI',
    get_certificate: '🎓 Dapatkan Sertifikat',
    course_complete_title: '🏅 Kursus Selesai!',
    course_complete_body: 'Anda telah menyelesaikan semua pelajaran dalam kursus ini. Luar biasa!',

    // Lesson page
    back_to_course: 'Kembali ke Kursus',
    complete_lesson: 'Selesaikan Pelajaran',
    already_completed: 'Sudah Selesai',
    next: 'Selanjutnya',
    previous: 'Sebelumnya',
    processing: 'Memproses...',
    what_youll_learn: 'Yang akan kamu pelajari dalam pelajaran ini',
    how_was_lesson: 'Bagaimana pelajaran ini?',
    thanks_feedback: '✅ Terima kasih atas masukanmu!',
    lesson_label: 'Pelajaran',
    of: 'dari',
    watch_on: 'Tonton di',

    // Labs
    run_code: 'Jalankan Kode',
    submit_task: 'Kirim Tugas',
    reset: 'Reset',
    terminal: 'Terminal',
    ai_hints: 'Petunjuk AI',
    reveal_hint: 'Tampilkan Petunjuk',
    all_hints_revealed: 'Semua petunjuk ditampilkan. Kamu pasti bisa! 💪',
    mission_accomplished: 'Misi Berhasil! 🏅',
    return_to_hub: 'Kembali ke Hub',
    ai_feedback: 'Umpan Balik AI Reviewer',
    running: 'Menjalankan…',

    // Onboarding
    onboard_title_1: 'Selamat datang di Promptara!',
    onboard_sub_1: 'Akademi Coding AI-mu',
    onboard_title_2: 'Cara Kerja',
    onboard_sub_2: 'Belajar dalam 4 langkah mudah',
    onboard_title_3: 'XP & Level Dijelaskan',
    onboard_sub_3: 'Progresmu, dalam bentuk permainan',
    onboard_title_4: 'Kamu Siap!',
    onboard_sub_4: 'Waktunya memulai pelajaran pertamamu',
    onboard_start: '🚀 Mulai Belajar!',
    onboard_next: 'Lanjut',
    onboard_back: '← Kembali',

    // Notifications
    notif_title: 'Notifikasi',
    notif_subtitle: 'Aktivitas terbaru',
    notif_empty: 'Belum ada aktivitas. Mulai pelajaran!',
    notif_footer: 'Hanya penyelesaian pelajaran yang ditampilkan',
    notif_completed: 'Selesai',

    // Guided tour
    tour_dont_show: 'Jangan tampilkan lagi',
    tour_done: '✓ Selesai',
    tour_next: 'Lanjut',

    // Page titles
    page_dashboard: 'Dasbor',
    page_dashboard_sub: 'Selamat datang kembali! Terus belajar.',
    page_courses: 'Kursus',
    page_courses_sub: 'Jelajahi dan lanjutkan perjalanan belajarmu',
    page_labs: 'Laboratorium',
    page_labs_sub: 'Simulasi dan tantangan berbasis praktik',
    page_leaderboard: 'Papan Peringkat',
    page_leaderboard_sub: 'Vibe coder terbaik bulan ini',
    page_profile: 'Profil Saya',
    page_profile_sub: 'Statistik belajar dan pencapaianmu',
    page_users: 'Manajemen Pengguna',
    page_users_sub: 'Kelola anggota platform',
    page_builder: 'Pembuat Kursus',
    page_builder_sub: 'Buat dan kelola konten kursus',
    page_analytics: 'Analitik',
    page_analytics_sub: 'Penggunaan platform dan wawasan',
    page_subs: 'Langganan',
    page_subs_sub: 'Kelola paket SaaS dan penagihan',

    // XP
    xp_level: 'Level',
    xp_to_next: 'ke berikutnya',

    // Lesson details & Quiz
    time_min: 'menit',
    quiz_req: 'Kuis — 80% untuk lulus',
    watch_read: 'Tonton & Baca',
    read_practice: 'Baca & Praktik',
    xp_on_completion: 'XP saat selesai',
    your_turn: 'Giliran Kamu!',
    correct: 'Benar!',
    correct_answer: 'Jawaban yang benar:',
    type_answer: 'Ketik jawabanmu...',
    true_ans: 'Benar',
    false_ans: 'Salah',
    check: 'Cek',

    // Sprint 1 — Friendly Microcopy
    start_here_title: '👋 Baru di sini? Mulai dari sini dulu!',
    start_here_sub: 'Jangan khawatir, tidak perlu pengalaman coding sama sekali. Kita mulai dari dasar bersama!',
    start_here_cta: 'Lihat Semua Kursus Pemula →',
    no_course_active: 'Kamu belum mulai kursus apa pun. Yuk mulai perjalananmu! 🚀',
    browse_free: 'Jelajahi Kursus Gratis →',
    complete_lesson_cta: 'Tandai Selesai & Dapatkan',
    error_generic: 'Terjadi kesalahan. Coba refresh halaman ya 🙏',
    no_results_search: 'Hmm, tidak ada yang cocok. Coba hapus filter atau cari dengan kata lain!',
    quiz_score_live: 'benar sejauh ini',
    quiz_need_more: 'lagi untuk lulus',
    quiz_ready_to_pass: 'Kamu hampir lulus! ✅',
    quiz_all_correct: 'Sempurna! 🎉',
    xp_benefits_title: 'Apa yang XP buka untukmu',
    xp_benefits_sub: 'Terus belajar untuk mencapai milestone baru',
    xp_benefit_1: 'Akses semua kursus Pemula',
    xp_benefit_2: 'Buka kursus Menengah',
    xp_benefit_3: 'Akses Labs eksklusif',
    xp_benefit_4: 'Dapatkan sertifikat digital',
    xp_benefit_5: 'Badge "Vibe Coder" + prioritas support',
    nav_courses_sub: 'Materi belajar',
    nav_labs_sub: 'Praktek coding',
    nav_leaderboard_sub: 'Peringkat kamu',
    nav_dashboard_sub: 'Ringkasan aktivitas',
    nav_profile_sub: 'Pengaturan & statistik',
    streak_day: 'hari berturut-turut',
    streak_days: 'hari berturut-turut',

    // Sprint 2 - Weekly challenge & Roadmap & Badges
    weekly_challenge_title: 'Tantangan Mingguan Pribadi',
    weekly_challenge_sub: 'Jaga momentum belajarmu! Selesaikan pelajaran untuk mendapat bonus XP.',
    weekly_challenge_target: 'Selesaikan 3 pelajaran minggu ini',
    weekly_challenge_reward: 'Hadiah:',
    weekly_challenge_deadline: 'Berakhir pada',
    weekly_challenge_completed: 'Tantangan Selesai! 🎉',
    weekly_challenge_progress: 'pelajaran selesai',
    
    badge_locked_title: 'Pencapaian & Lencana',
    badge_locked_subtitle: 'Tunjukkan progresmu dan buka status khusus',
    badge_condition_first_lab: 'Selesaikan lab praktik pertamamu',
    badge_condition_graduate_1: 'Selesaikan 1 kursus',
    badge_condition_graduate_2: 'Selesaikan 2 kursus',
    badge_condition_graduate_3: 'Selesaikan 3 kursus',
    badge_condition_graduate_4: 'Selesaikan 4 kursus',
    badge_condition_graduate_5: 'Selesaikan 5 kursus',
    badge_condition_speed_demon: 'Selesaikan 3 pelajaran dalam satu hari',
    badge_condition_perfectionist: 'Dapatkan skor sempurna 100% di kuis',
    
    roadmap_title: 'Peta Jalan Belajar',
    roadmap_sub: 'Jalur panduanmu dari pemula mutlak hingga pembuat mahir',
    roadmap_tier_beginner: '🌱 Pemula',
    roadmap_tier_explorer: '🔥 Penjelajah',
    roadmap_tier_vibecoder: '🚀 Vibe Coder',
    roadmap_tier_advanced: '💡 Pembuat Mahir',
    roadmap_tier_desc_beginner: 'Dasar TI & Pengenalan',
    roadmap_tier_desc_explorer: 'Dasar-Dasar Prompting',
    roadmap_tier_desc_vibecoder: 'Pengembangan Aplikasi AI',
    roadmap_tier_desc_advanced: 'Produksi & Penyebaran',
    roadmap_here: 'Kamu di sini',
    
    quiz_review_title: 'Mode Tinjauan',
    quiz_review_subtitle: 'Tinjau pertanyaan yang salah dan coba lagi!',
    quiz_try_again: 'Coba Lagi',

    // Course Quizzes
    'In the Vibe Coding paradigm, what is the primary role of the human developer?': 'Dalam paradigma Vibe Coding, apa peran utama pengembang manusia?',
    'Writing boilerplate code manually': 'Menulis kode boilerplate secara manual',
    'Memorizing syntax': 'Menghafal sintaks',
    'Acting as the Director and Architect': 'Bertindak sebagai Direktur dan Arsitek',
    'Replacing the compiler': 'Menggantikan kompiler',
    'The human transitions from being the typist to being the architect, focusing on system design and validation.': 'Manusia bertransisi dari pengetik menjadi arsitek, berfokus pada desain sistem dan validasi.',
    'AI models have perfect memory of your codebase once you start a conversation.': 'Model AI memiliki memori sempurna tentang basis kode Anda begitu Anda memulai percakapan.',
    'AI models are stateless. You must load context explicitly in every session or conversation.': 'Model AI bersifat stateless. Anda harus memuat konteks secara eksplisit di setiap sesi atau percakapan.',
    'Arrange these Vibe Coding workflow steps in the correct order:': 'Urutkan langkah-langkah alur kerja Vibe Coding ini dalam urutan yang benar:',
    'Step 1: Define the goal and scope of the feature': 'Langkah 1: Tentukan tujuan dan cakupan fitur',
    'Step 2: Load context — describe tech stack and constraints': 'Langkah 2: Muat konteks — jelaskan tumpukan teknologi dan batasan',
    'Step 3: Write a specific, scoped prompt to the AI': 'Langkah 3: Tulis prompt yang spesifik dan terarah ke AI',
    'Step 4: Review every line of the AI-generated code': 'Langkah 4: Tinjau setiap baris kode yang dihasilkan AI',
    'Step 5: Commit the working code to Git': 'Langkah 5: Commit kode yang berfungsi ke Git',
    'The correct order ensures the AI has all context before generating, and you verify before shipping.': 'Urutan yang benar memastikan AI memiliki semua konteks sebelum menghasilkan kode, dan Anda memverifikasi sebelum mengirimkannya.',
    'What is the main benefit of Chain of Thought (CoT) prompting?': 'Apa manfaat utama dari prompting Chain of Thought (CoT)?',
    'It uses fewer tokens': 'Menggunakan lebih sedikit token',
    'It forces the model to write out reasoning steps, reducing logical errors': 'Ini memaksa model untuk menuliskan langkah-langkah penalaran, mengurangi kesalahan logis',
    'It guarantees 100% secure code': 'Menjamin 100% kode aman',
    'It prevents the model from using external tools': 'Ini mencegah model menggunakan alat eksternal',
    'CoT allows the model to "show its work", which drastically improves its ability to solve complex logical problems.': 'CoT memungkinkan model untuk "menunjukkan kerjanya", yang secara drastis meningkatkan kemampuannya untuk menyelesaikan masalah logis yang kompleks.',
    'Which of the following is an example of Few-Shot Prompting?': 'Manakah dari berikut ini yang merupakan contoh Few-Shot Prompting?',
    '"Write a web server in Go."': '"Tulis server web di Go."',
    '"Let\'s think step by step."': '"Mari kita berpikir langkah demi langkah."',
    'Providing 3 examples of inputs and desired outputs before asking the real question.': 'Menyediakan 3 contoh input dan output yang diinginkan sebelum menanyakan pertanyaan sebenarnya.',
    '"Act as a senior engineer."': '"Bertindak sebagai insinyur senior."',
    'Few-shot prompting relies on providing concrete examples (shots) to guide the model\'s output formatting.': 'Few-shot prompting bergantung pada penyediaan contoh konkret (shots) untuk memandu pemformatan output model.',
    'Why should you avoid asking the AI to "build the whole app" in one prompt?': 'Mengapa Anda harus menghindari meminta AI untuk "membangun seluruh aplikasi" dalam satu prompt?',
    'Because it costs too much money': 'Karena biayanya terlalu mahal',
    'Because of token limits and attention degradation leading to poor code quality': 'Karena batasan token dan penurunan perhatian yang menyebabkan kualitas kode buruk',
    'Because AI cannot write full apps': 'Karena AI tidak dapat menulis aplikasi lengkap',
    'Because the compiler will reject it': 'Karena kompiler akan menolaknya',
    'LLMs perform best on scoped, modular tasks. Asking for massive files at once leads to errors and truncated code.': 'LLM bekerja paling baik pada tugas-tugas yang terarah dan modular. Meminta file besar sekaligus menyebabkan kesalahan dan kode terpotong.',
    'What is the recommended way to fix a broken UI generated by AI?': 'Apa cara yang disarankan untuk memperbaiki UI rusak yang dihasilkan oleh AI?',
    'Spend hours manually reading CSS documentation': 'Menghabiskan waktu berjam-jam membaca dokumentasi CSS secara manual',
    'Delete the project and start over': 'Hapus proyek dan mulai dari awal',
    'Provide the AI with a screenshot of the broken UI and ask it to fix the layout': 'Berikan AI tangkapan layar UI yang rusak dan minta untuk memperbaiki tata letaknya',
    'Switch to a different programming language': 'Beralih ke bahasa pemrograman lain',
    'Using Multimodal (Vision) AI is the fastest way to debug visual alignment and CSS issues.': 'Menggunakan AI Multimodal (Visi) adalah cara tercepat untuk men-debug penyelarasan visual dan masalah CSS.',
    'What is a "hallucination" in the context of AI coding?': 'Apa yang dimaksud dengan "halusinasi" dalam konteks coding AI?',
    'When the AI writes perfectly optimized code': 'Ketika AI menulis kode yang dioptimalkan dengan sempurna',
    'When the AI confidently generates code that uses non-existent functions or libraries': 'Ketika AI dengan percaya diri menghasilkan kode yang menggunakan fungsi atau pustaka yang tidak ada',
    'When the AI refuses to answer': 'Ketika AI menolak untuk menjawab',
    'When the AI deletes your files': 'Ketika AI menghapus file Anda',
    'Hallucinations occur when the model predicts tokens that look plausible but are factually incorrect or reference non-existent APIs.': 'Halusinasi terjadi ketika model memprediksi token yang terlihat masuk akal tetapi secara faktual salah atau merujuk ke API yang tidak ada.',
    'What is the best defense against AI hallucinations in JavaScript?': 'Apa pertahanan terbaik terhadap halusinasi AI di JavaScript?',
    'Using TypeScript for static type checking': 'Menggunakan TypeScript untuk pemeriksaan tipe statis',
    'Using `var` instead of `const`': 'Menggunakan `var` alih-alih `const`',
    'Writing all code in a single file': 'Menulis semua kode dalam satu file',
    'Never using AI': 'Tidak pernah menggunakan AI',
    'TypeScript catches hallucinations at compile time by ensuring the AI-generated code adheres to defined interfaces and types.': 'TypeScript menangkap halusinasi pada saat kompilasi dengan memastikan kode yang dihasilkan AI mematuhi antarmuka dan tipe yang ditentukan.',
    'What is Prompt Injection?': 'Apa itu Prompt Injection?',
    'Injecting SQL commands into a database': 'Menyuntikkan perintah SQL ke dalam database',
    'When a user crafts input that overrides the LLM system instructions to make it perform unauthorized actions': 'Ketika pengguna membuat input yang mengabaikan instruksi sistem LLM untuk membuatnya melakukan tindakan tidak sah',
    'A way to make the AI respond faster': 'Cara membuat AI merespons lebih cepat',
    'Injecting CSS into a webpage': 'Menyuntikkan CSS ke dalam halaman web',
    'Prompt injection is unique to LLMs, where untrusted user input tricks the model into ignoring its original constraints.': 'Prompt injection unik untuk LLM, di mana input pengguna yang tidak tepercaya mengelabui model untuk mengabaikan batasan aslinya.',
    'How should you handle the output of an LLM before using it to execute a system command or database query?': 'Bagaimana Anda harus menangani output LLM sebelum menggunakannya untuk mengeksekusi perintah sistem atau kueri database?',
    'Trust it completely if it comes from GPT-4': 'Percayai sepenuhnya jika itu berasal dari GPT-4',
    'Pass it directly to the database': 'Kirimkan langsung ke database',
    'Force structured JSON output and strictly validate it against a predefined schema': 'Paksa output JSON terstruktur dan validasi secara ketat terhadap skema yang telah ditentukan sebelumnya',
    'Only run it on Tuesdays': 'Hanya jalankan pada hari Selasa',
    'Never trust LLM output. Always force a structured format (like JSON) and validate it using a schema validation library before execution.': 'Jangan pernah memercayai output LLM. Selalu paksa format terstruktur (seperti JSON) dan validasi menggunakan pustaka validasi skema sebelum dieksekusi.',

    // Learning Resources
    'Review: Vibe Coding Overview': 'Tinjauan: Ringkasan Vibe Coding',
    'What is Vibe Coding? (GitHub Blog)': 'Apa itu Vibe Coding? (GitHub Blog)',
    'GitHub Copilot Documentation': 'Dokumentasi GitHub Copilot',
    'Awesome AI Dev Tools': 'Alat Pengembangan AI yang Luar Biasa',
    'Course Companion Notes': 'Catatan Pendamping Kursus',
    'Lesson Cheatsheet': 'Lembar Sontekan Pelajaran',
    'Review the Lesson Content': 'Tinjau Konten Pelajaran',
    'Quiz Strategies for Beginners': 'Strategi Kuis untuk Pemula',

    // Resource Types
    Docs: 'Dokumentasi',
    Repository: 'Repositori',
    Cheatsheet: 'Lembar Panduan',
    Article: 'Artikel',
    Download: 'Unduhan',

    // Sprint 3 - Labs sorting, Guided Mode, Explain Code, Certificate
    sort_by_level: 'Urutkan Level:',
    sort_default: 'Bawaan',
    sort_beginner_first: '🌱 Pemula Dulu',
    sort_advanced_first: '🚀 Mahir Dulu',
    guided_mode_toggle: 'Mode Panduan',
    expert_mode: 'Pakar',
    guided_mode: 'Panduan',
    guided_checklist_title: 'Checklist Panduan',
    guided_checklist_subtitle: 'Instruksi langkah demi langkah untuk membantumu menyelesaikan lab ini',
    explain_code_btn: '💡 Jelaskan Kode',
    explain_code_title: 'Penjelasan Kode',
    explain_code_subtitle: 'Penjelasan baris demi baris dari kode awal Anda dalam bahasa sederhana',
    explain_code_close: 'Tutup',
    certificate_modal_title: 'PROMPTARA SERTIFIKAT KELULUSAN',
    certificate_presented_to: 'Dengan bangga dipersembahkan kepada',
    certificate_course_completed: 'karena telah berhasil menyelesaikan kursus',
    certificate_role: 'Certified Digital Builder (Pembangun Digital Terpadu)',
    certificate_date: 'Tanggal Kelulusan',
    certificate_id: 'ID Kredensial',
    certificate_print: 'Simpan Sertifikat (PDF)',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('vl_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('vl_lang', lang);
    document.documentElement.setAttribute('lang', lang);
  }, [lang]);

  const t = (key) => TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;

  const toggleLang = () => setLang(l => l === 'en' ? 'id' : 'en');

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
